### ISSUE TITLE
Mirror configuration from other repos for the PR flow

### ISSUE THREAD

**Issue by derberg** [kyma-project/bundles#5]
Make sure you have proper setting in PR flow:
- for mandatory review requirement,
- ci status requirement
- cla sign up requirement

**Comment by mszostok** [comment]
#### Introduced changes in repo settings:
[Options](https://github.com/kyma-project/kyma/settings):
- Disable **Wikis feature**
- Disable **Allow merge commits** and **Allow rebase merging** buttons.

[Colaborators](https://github.com/kyma-project/kyma/settings/collaboration):
- Add for all people from CODEOWNER the **Write** permission.

[Branches](https://github.com/kyma-project/bundles/settings/branches):
- Require pull request reviews before merging (1 approving person and he/she needs to be a code owner)
- Require status checks to pass before merging (Travis CI - Pull Request and license/cla) - also including administrators

>NOTE: Currently it's configured only for master branch. When we go with the release branches then we need to add new rule for them (we can use regex for branch name e.g. release-*, and then the rules will be added for all new releases automatically)

Introduced chagnes were tested on this PR: https://github.com/kyma-project/bundles/pull/20
