### ISSUE TITLE
Provide documentation for the testing bundle

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/bundles#79]
**Description**

It would be good for a test to extend our testing bundle with documentation under the `docs` folder. It's explained in this comment: https://github.com/kyma-project/kyma/pull/3804#pullrequestreview-230327157

**Reasons**

We or the guys working on the console might have a case in the future to test how documentation is displayed on the console also our testing bundle with `full` plan assumes it supports all features so it also should have documentation.

**Comment by derberg** [comment]
- Probably best is to extend existing tutorial (under Helm Broker component) about how to write docs for bundle
- link to test bundle with docs from tutorial
- have test markdowns in testing bundle https://github.com/kyma-project/bundles/tree/master/bundles/testing-0.0.1 with some test image. It can be generated with some lorem ipsum like https://ipsum-community.github.io/hodoripsum/ (although I'm afraid Hodor doesn't generate to complicated markdown :)). You can see how it is realized in https://github.com/kyma-project/bundles/tree/master/bundles/redis-0.0.3
- add dummy petstore open api spec and dummy streetlight asyncapi spec:
  - https://petstore.swagger.io/v2/swagger.json
  - https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/1.2.0/streetlights.yml
- have UI tests that checks if documentation is rendered and images are not broken
