### ISSUE TITLE
Move redis addon from index.yaml to index-testing.yaml

### ISSUE THREAD

**Issue by PK85** [kyma-project/bundles#86]
**Description**
Redis addon will be not in our main index.yaml anymore. We need to move it to index-testing.yaml and refactor tests to enable redis for them.

**AC**
- move addon from one index to another
- list all tests that use redis addon then keep them green by activation index-testing.yaml in test suite
- find all references where redis bundle is used, especially in examples repository and mention about repoURL activation
- release new bundles version, mainly update version 0.6.0 which will be used with Kyma 1.2

**Comment by polskikiel** [comment]
Tests which are using the `testing` bundle and contains logic to create a config map with it:
- UI acceptance
- ConsoleBackendService acceptance tests
We must remove this logic from the above tests.

Tests which using the `redis` bundle:
- backup-restore test
- upgrade test

The `redis` `ClusterServiceClass` must be created in the `testing.sh` script before the tests are executed.
